version: 2.1

jobs:
  step-a:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: print BASH_ENV location
          command: |
            echo $BASH_ENV
      - run:
          name: Save COLOR to BASH_ENV
          command: |
            echo "export COLOR=${COLOR}" >> $BASH_ENV
          environment:
            COLOR: "green"
      - run:
          name: Print COLOR
          command: |
            echo $COLOR

  step-b:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: print BASH_ENV location
          command: |
            echo $BASH_ENV
      - run:
          name: See env vars
          command: |
            env

workflows:
  main:
    jobs:
      - step-a
      - step-b
